# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ethan/YODA_R2D2/YODA_R2D2.srcs/sources_1/ip/AddressLUT/AddressLUT.xci
# IP: The module: 'AddressLUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ethan/YODA_R2D2/YODA_R2D2.srcs/sources_1/ip/AddressLUT/AddressLUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AddressLUT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/ethan/YODA_R2D2/YODA_R2D2.srcs/sources_1/ip/AddressLUT/AddressLUT.xci
# IP: The module: 'AddressLUT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ethan/YODA_R2D2/YODA_R2D2.srcs/sources_1/ip/AddressLUT/AddressLUT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AddressLUT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
